import { createApp } from 'vue'
import { createPinia } from 'pinia'
import './style.css'
import App from './App.vue'
import router from './router'
import 'viewerjs/dist/viewer.css'
import VueViewer from 'v-viewer'
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'
// Import the functions you need from the SDKs you need
import { initializeApp } from 'firebase/app'
import { getAnalytics } from 'firebase/analytics'
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: 'AIzaSyCmtsTYySDPpIQ6ASIn0N9LHFqUwm-MLLo',
  authDomain: 'mis-reclamos.firebaseapp.com',
  projectId: 'mis-reclamos',
  storageBucket: 'mis-reclamos.firebasestorage.app',
  messagingSenderId: '3807456076',
  appId: '1:3807456076:web:3bfab857b83e51a6217de9',
  measurementId: 'G-CM4YRNN50E',
}

// Initialize Firebase
const firebaseApp = initializeApp(firebaseConfig)
const analytics = getAnalytics(firebaseApp)

import { OhVueIcon, addIcons } from 'oh-vue-icons'
import {
  FaFlag,
  RiZhihuFill,
  // Font Awesome (fa-*)
  FaShoppingBasket,
  FaWineBottle,
  FaBeer,
  FaGlassMartini,
  FaBreadSlice,
  FaShieldAlt,
  FaCar,
  FaPiggyBank,
  FaUtensils,
  FaHardHat,
  FaSoap,
  FaFutbol,
  FaGraduationCap,
  FaLaptop,
  FaLeaf,
  FaTicketAlt,
  FaPills,
  FaTools,
  FaLandmark,
  FaBed,
  FaGem,
  FaGamepad,
  FaShoppingCart,
  FaIdCard,
  FaStickyNote,
  FaTruck,
  FaUser,
  FaBoxOpen,
  FaHeart,
  FaChurch,
  FaTshirt,
  FaHospital,
  FaSpa,
  FaConciergeBell,
  FaFilm,
  FaCode,
  FaCartPlus,
  FaMicrochip,
  FaPhoneAlt,
  FaStore,
  FaBaby,
  FaBus,
  FaUmbrellaBeach,
  FaDog,
  HiSolidLightBulb,
  HiSolidOfficeBuilding,
  HiSolidDesktopComputer,
  HiSolidSparkles,
  HiSolidHashtag,
  HiSolidGlobe,
  FaWrench,
  GiMilkCarton,
  LaToolsSolid,
  BiBank2,
  RiGovernmentLine,
  IoChatbubbles,
  BiMailbox2,
  MdHealthandsafety,
  FaBusAlt,
  MdLivetvTwotone,
  GiElectricalResistance,
  RiHotelLine,
  IoRestaurant,
  FaBalanceScale,
  FaGasPump,
  MdBuildSharp,
  IoShareSocialSharp,
  GiClothes,
  MdTravelexploreSharp,
  IoPawSharp,
  MdAddRound,
  MdTextrotationnoneRound,
  MdAlternateemailOutlined,
  GiMegaphone,
  HiMenu,
  IoClose,
  RiLoader5Fill,
  HiCalendar,
  HiUser,
  HiOfficeBuilding,
  HiDocumentText,
  HiTag,
  HiEye,
  FaUserEdit,
  RiShieldUserFill,
  LaUserTieSolid,
  BiCalendar3,
  BiCalendar4Range
} from 'oh-vue-icons/icons'

addIcons(
  FaFlag,
  RiZhihuFill,
  // Font Awesome (fa-*)
  FaShoppingBasket,
  FaWineBottle,
  FaBeer,
  FaGlassMartini,
  FaBreadSlice,
  FaShieldAlt,
  FaCar,
  FaPiggyBank,
  FaUtensils,
  FaHardHat,
  FaSoap,
  FaFutbol,
  FaGraduationCap,
  FaLaptop,
  FaLeaf,
  FaTicketAlt,
  FaPills,
  FaTools,
  FaLandmark,
  FaBed,
  FaGem,
  FaGamepad,
  FaShoppingCart,
  FaIdCard,
  FaStickyNote,
  FaTruck,
  FaUser,
  FaBoxOpen,
  FaHeart,
  FaChurch,
  FaTshirt,
  FaHospital,
  FaSpa,
  FaConciergeBell,
  FaFilm,
  FaCode,
  FaCartPlus,
  FaMicrochip,
  FaPhoneAlt,
  FaStore,
  FaBaby,
  FaBus,
  FaUmbrellaBeach,
  FaDog,
  // Heroicons (hi-Solid-*)
  HiSolidLightBulb,
  FaWrench,
  HiSolidOfficeBuilding,
  HiSolidDesktopComputer,
  HiSolidSparkles,
  HiSolidHashtag,
  HiSolidGlobe,
  GiMilkCarton,
  LaToolsSolid,
  BiBank2,
  RiGovernmentLine,
  IoChatbubbles,
  BiMailbox2,
  MdHealthandsafety,
  FaBusAlt,
  MdLivetvTwotone,
  GiElectricalResistance,
  RiHotelLine,
  IoRestaurant,
  FaBalanceScale,
  FaGasPump,
  MdBuildSharp,
  IoShareSocialSharp,
  GiClothes,
  MdTravelexploreSharp,
  IoPawSharp,
  MdAddRound,
  MdTextrotationnoneRound,
  MdAlternateemailOutlined,
  GiMegaphone,
  HiMenu,
  IoClose,
  RiLoader5Fill,
  HiCalendar,
  HiUser,
  HiOfficeBuilding,
  HiDocumentText,
  HiTag,
  HiEye,
  FaUserEdit,
  RiShieldUserFill,
  LaUserTieSolid,
  BiCalendar3,
  BiCalendar4Range
)

const pinia = createPinia()
pinia.use(piniaPluginPersistedstate)
const app = createApp(App)

app.use(VueViewer)
app.use(pinia)
app.use(router)
app.component('v-icon', OhVueIcon)
app.mount('#app')
