import { createApp } from 'vue'
import { createPinia } from 'pinia'
import './style.css'
import App from './App.vue'
import router from './router'

import { OhVueIcon, addIcons } from "oh-vue-icons";
import { FaFlag, RiZhihuFill,
  // Font Awesome (fa-*)
  FaShoppingBasket,
  FaWineBottle,
  FaBeer,
  FaGlassMartini,
  FaBreadSlice,
  FaShieldAlt,
  FaCar,
  FaPiggyBank,
  FaUtensils,
  FaHardHat,
  FaSoap,
  FaFutbol,
  FaGraduationCap,
  FaLaptop,
  FaLeaf,
  FaTicketAlt,
  FaPills,
  FaTools,
  FaLandmark,
  FaBed,
  FaGem,
  FaGamepad,
  FaShoppingCart,
  FaIdCard,
  FaStickyNote,
  FaTruck,
  FaUser,
  FaBoxOpen,
  FaHeart,
  FaChurch,
  FaTshirt,
  FaHospital,
  FaSpa,
  FaConciergeBell,
  FaFilm,
  FaCode,
  FaCartPlus,
  FaMicrochip,
  FaPhoneAlt,
  FaStore,
  FaBaby,
  FaBus,
  FaUmbrellaBeach,
  FaDog,
  // Heroicons (hi-outline-*)
  HiSolidLightBulb,
  HiSolidOfficeBuilding,
  HiSolidDesktopComputer,
  HiSolidSparkles,
  HiSolidHashtag,
  HiSolidGlobe,
  FaWrench,
  GiMilkCarton,
  LaToolsSolid,
  BiBank2,
  RiGovernmentLine,
  IoChatbubbles,
  BiMailbox2,
  MdHealthandsafety,
  FaBusAlt,
  MdLivetvTwotone,
  GiElectricalResistance,
  RiHotelLine,
  IoRestaurant,
  FaBalanceScale,
  FaGasPump,
  MdBuildSharp,
  IoShareSocialSharp,
  GiClothes,
  MdTravelexploreSharp,
  IoPawSharp,
  MdAddRound
 } from "oh-vue-icons/icons";

addIcons(FaFlag, RiZhihuFill,
  // Font Awesome (fa-*)
  FaShoppingBasket,
  FaWineBottle,
  FaBeer,
  FaGlassMartini,
  FaBreadSlice,
  FaShieldAlt,
  FaCar,
  FaPiggyBank,
  FaUtensils,
  FaHardHat,
  FaSoap,
  FaFutbol,
  FaGraduationCap,
  FaLaptop,
  FaLeaf,
  FaTicketAlt,
  FaPills,
  FaTools,
  FaLandmark,
  FaBed,
  FaGem,
  FaGamepad,
  FaShoppingCart,
  FaIdCard,
  FaStickyNote,
  FaTruck,
  FaUser,
  FaBoxOpen,
  FaHeart,
  FaChurch,
  FaTshirt,
  FaHospital,
  FaSpa,
  FaConciergeBell,
  FaFilm,
  FaCode,
  FaCartPlus,
  FaMicrochip,
  FaPhoneAlt,
  FaStore,
  FaBaby,
  FaBus,
  FaUmbrellaBeach,
  FaDog,
  // Heroicons (hi-Solid-*)
  HiSolidLightBulb,
  FaWrench,
  HiSolidOfficeBuilding,
  HiSolidDesktopComputer,
  HiSolidSparkles,
  HiSolidHashtag,
  HiSolidGlobe,
  GiMilkCarton,
  LaToolsSolid,
  BiBank2,
  RiGovernmentLine,
  IoChatbubbles,
  BiMailbox2,
  MdHealthandsafety,
  FaBusAlt,
  MdLivetvTwotone,
  GiElectricalResistance,
  RiHotelLine,
  IoRestaurant,
  FaBalanceScale,
  FaGasPump,
  MdBuildSharp,
  IoShareSocialSharp,
  GiClothes,
  MdTravelexploreSharp,
  IoPawSharp,
  MdAddRound

);

const app = createApp(App)

app.use(createPinia())
app.use(router)
app.component("v-icon", OhVueIcon);
app.mount('#app')
